logging:
  level:
    ROOT: DEBUG
    com.jani: DEBUG

messaging:
  from: domyjacek@op.pl
  to: jniedzwiecki83@gmail.com,jniedzwiecki@op.pl
  subject: Domki
  hostname: smtp.poczta.onet.pl

database:
  url: jdbc:mysql://localhost/houses?serverTimezone=CET
  name: houses

excludes: Złotno,Koziny,Szaserów
