logging:
  level:
    ROOT: DEBUG
    com.jani: DEBUG

messaging:
  from: domyjacek@op.pl
  to: jniedzwiecki83@gmail.com,jniedzwiecki@op.pl
  subject: Domki
  hostname: smtp.poczta.onet.pl

excludes: Złotno,Koziny,Szaserów

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/houses?serverTimezone=CET
    username: houses